"""
Helper script to document all output files generated by the analysis.

This script lists all CSV and PDF files that will be generated when running
the analysis scripts. FINDINGS_EXPLANATION.md is preserved and not overwritten.
"""

OUTPUT_FILES = {
    'rq1': {
        'description': 'RQ1: Performance improvement patterns',
        'csv_files': [
            'raw_data_athlete_features.csv',
            'raw_data_feature_importance.csv',
            'raw_data_model_performance.csv',
            'raw_data_3year_validation_results.csv',
            'raw_data_important_statistics.csv',
            'raw_data_gender_feature_importance_comparison.csv',
            'raw_data_gender_feature_importance_pivot.csv',
            'raw_data_subgroup_analysis.csv',
            'time_standardization_comparison.csv',
        ],
        'pdf_files': [
            'raw_data_feature_importance.pdf',
            'raw_data_gender_feature_importance_comparison.pdf',
            'raw_data_residual_diagnostics.pdf',
            'raw_data_model_predictions.pdf',
            'raw_data_model_predictions_gradient_boosting.pdf',
            'raw_data_model_predictions_random_forest.pdf',
            'raw_data_model_predictions_linear_regression.pdf',
            'raw_data_model_predictions_ridge_regression.pdf',
            'raw_data_model_predictions_lasso_regression.pdf',
            'raw_data_model_predictions_svr.pdf',
            'raw_data_model_predictions_all_models_men.pdf',
            'raw_data_model_predictions_all_models_women.pdf',
            'time_standardization_comparison.pdf',
        ],
        'subdirectories': [
            'first_to_last_improvement/',  # Contains PDFs for each year
            'number_of_races_question/',  # Contains CSVs for race count analysis
        ]
    },
    'rq2': {
        'description': 'RQ2: Distribution of time changes between races',
        'csv_files': [
            'time_standardization_comparison.csv',  # Copied from rq1
        ],
        'pdf_files': [
            'time_standardization_comparison.pdf',  # Copied from rq1
        ],
        'subdirectories': [
            'percentile_time_analysis/',  # Contains CSVs: percentile_analysis_{year}_{gender}_{mode}.csv
        ]
    },
    'rq3': {
        'description': 'RQ3: Gender differences in participation and performance',
        'csv_files': [
            'raw_data_gender_feature_importance_comparison.csv',  # Copied from rq1
            'raw_data_gender_feature_importance_pivot.csv',  # Copied from rq1
        ],
        'pdf_files': [
            'raw_data_gender_feature_importance_comparison.pdf',  # Copied from rq1
        ],
        'subdirectories': [
            'gender_analysis/',  # Contains: gender_race_participation.csv, gender_analysis_summary.csv
        ]
    },
    'output': {
        'description': 'General outputs (charts and summaries)',
        'csv_files': [
            'research_summary_table.csv',
        ],
        'pdf_files': [
            'research_model_performance.pdf',
            'research_feature_importance.pdf',
            'research_improvement_distributions.pdf',
            'research_improvement_trends.pdf',
            'research_model_comparison.pdf',
            'research_feature_analysis.pdf',
            'research_model_formula.pdf',
        ],
        'subdirectories': []
    }
}

def print_output_summary():
    """Print a summary of all output files."""
    print("="*60)
    print("OUTPUT FILES SUMMARY")
    print("="*60)
    print("\nNote: FINDINGS_EXPLANATION.md is preserved and not overwritten.")
    print("\nAll other files in output/ will be regenerated when scripts are run.\n")
    
    total_csv = 0
    total_pdf = 0
    
    for location, info in OUTPUT_FILES.items():
        print(f"\n{location.upper()}/ - {info['description']}")
        print("-" * 60)
        
        if info['csv_files']:
            print(f"\nCSV Files ({len(info['csv_files'])}):")
            for csv in info['csv_files']:
                print(f"  - {csv}")
                total_csv += 1
        
        if info['pdf_files']:
            print(f"\nPDF Files ({len(info['pdf_files'])}):")
            for pdf in info['pdf_files']:
                print(f"  - {pdf}")
                total_pdf += 1
        
        if info['subdirectories']:
            print(f"\nSubdirectories ({len(info['subdirectories'])}):")
            for subdir in info['subdirectories']:
                print(f"  - {subdir}")
                print(f"    (Contains additional CSV/PDF files)")
    
    print("\n" + "="*60)
    print(f"TOTAL: {total_csv} CSV files, {total_pdf} PDF files")
    print("="*60)
    print("\nTo regenerate all outputs (preserving FINDINGS_EXPLANATION.md):")
    print("  1. Delete all files in output/ except FINDINGS_EXPLANATION.md")
    print("  2. Run: python scripts/rq1.py")
    print("  3. Run: python scripts/rq2.py")
    print("  4. Run: python scripts/rq3.py")
    print("  5. Run: python scripts/create_charts.py")

if __name__ == "__main__":
    print_output_summary()

